version: '3.8'

services:
  web:
    image: node:20-bookworm
    restart: always
    environment:
      - PORT=3000
      - NODE_ENV=production
    command: node_modules/.bin/next start
    volumes:
      - .next:/app/.next
      - ./public:/app/public
    networks:
      - agent-net
    deploy:
      replicas: 1
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.reina-de-copas.entrypoints=websecure"
        - "traefik.http.routers.reina-de-copas.rule=Host(`reina-de-copas.paragu-ai.com`)"
        - "traefik.http.routers.reina-de-copas.tls=true"
        - "traefik.http.routers.reina-de-copas.tls.certresolver=letsencryptresolver"
        - "traefik.http.services.reina-de-copas.loadbalancer.server.port=3000"
        - "traefik.docker.network=agent-net"

networks:
  agent-net:
    external: true